apiVersion: v2
name: argocd-image-updater
version: 1.1.5
type: application

dependencies:
  - name: argocd-image-updater
    version: ~1.1.5
    repository: "https://argoproj.github.io/argo-helm"
    alias: app
