externalSecret:
  enabled: false
  secretStoreRef:
    name: aws-secrets-manager-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater
  data:
    - secretKey: CLOUDEVENTS_WEBHOOK_SECRET
      remoteRef:
        key: argocd-image-updater
        property: CLOUDEVENTS_WEBHOOK_SECRET

envFrom:
  - secretRef:
      name: argocd-image-updater

gatewayApi:
  httpRoute:
    enabled: false
    name: ""
    path: /webhook
    parentRefs: []
    hostnames: []
    rules: []
