apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: instance-manager-grafana-alloy
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: system-grafana-alloy
  podSelector:
    matchLabels:
      longhorn.io/component: instance-manager
  policyTypes:
  - Ingress
