app:
  metrics:
    serviceMonitor:
      enabled: true
  longhornManager:
    log:
      format: json
  longhornDriver:
    log:
      format: json
  longhornUI:
    replicas: 1
  networkPolicies:
    enabled: true
