{{- range $secret_store := $.Values.app.secretStores }}
{{- range $secret := $secret_store.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret_store.namespace }}
  labels: {{- include "secret-store.labels" $ | indent 4 }}
spec:
  secretStoreRef:
    name: {{ printf "%s-secret-store" $secret_store.name }}
    kind: SecretStore
  refreshInterval: "{{ default "1h" $secret.refreshInterval }}"
  target:
    name: {{ $secret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: {{ default "Opaque" $secret.template }}
  dataFrom:
  - extract:
      key: {{ $secret.key }}
      metadataPolicy: None
      decodingStrategy: None
      conversionStrategy: Default
{{- end }}
{{- end }}