{{- range $secret_store, $config := $.Values.app.secretStores }}
---
apiVersion: external-secrets.io/v1
kind: {{ default "SecretStore" $config.kind }}
metadata:
  name: {{ printf "%s-secret-store" $config.name }}
  namespace: {{ $config.namespace }}
  labels: {{- include "secret-store.labels" $ | indent 4 }}
spec:
  provider:
  {{/* AWS Configuration*/}}
    {{- if eq $.Values.app.provider "aws" }}
    aws:
      service: SecretsManager
      region: {{ $.Values.app.region }}
      {{- if $config.role }}
      role: {{ $config.role }}
      {{- end }}
    {{- end }}
  {{/* GitLab Configuration*/}}
  {{- if eq $.Values.app.provider "gitlab" }}
    gitlab:
      url: {{ default "https://skyloud.dev" $config.url }}
      auth:
        SecretRef:
          accessToken:
            name: {{ default "gitlab-token" $config.secret_name }}
            key: {{ default "token" $config.secret_key }}
      projectID: {{ $config.project_id }}
      groupIDs: {{ default "" $config.group_ids }}
      inheritFromGroups: {{ default "false" $config.inherit_from_groups }}
      environment: {{ default "" $config.environment }}
    {{- end }}
  {{/* Scaleway Configuration*/}}
  {{- if eq $.Values.app.provider "scw" }}
    scaleway:
      region: {{ $.Values.app.region }}
      projectId: {{ $config.project_id }}
      accessKey:
        secretRef:
          name: {{ $config.secret_name }}
          key: {{ default "access_key" $config.access_key }}
      secretKey:
        secretRef:
          name: {{ $config.secret_name }}
          key: {{ default "secret_key" $config.secret_key }}
    {{- end }}
{{- end }}