{
 "title": "Kubernetes / Single Node Overview",
 "description": "Node Exporter Dashboard for Kubernetes Environment. Displays key server resource metrics such as CPU, Memory, Disk, Network, Load, Connections, and Health Score in a tabular format for easy monitoring and analysis.",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$env\"},job)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$env\", job=~\"$job\"},nodename)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$env\", job=~\"$job\", nodename=~\"$name\"},instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "3m" },
   {
    "name": "total",
    "label": "Host Count",
    "query": {
     "query": "query_result(count(node_uname_info{env=~\"$env\",job=~\"$job\"}))"
    }
   },
   {
    "name": "device",
    "label": "Network Card",
    "query": {
     "query": "label_values(node_network_info{env=~\"$env\", job=~\"$job\", instance=~\"$instance\", device!~\"'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'\"},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "Max Mount Directory",
    "query": {
     "query": "query_result(topk(1,sort_desc(max(node_filesystem_size_bytes{env=~\"$env\",instance=~\"$instance\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "Display Name",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$env\", job=~\"$job\", nodename=~\"$name\", instance=~\"$instance\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview: [$env: $job] - [$show_name] - Node: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overview Table [Total Hosts: $total]",
   "type": "table",
   "description": "Partition usage, disk read, disk write, download bandwidth, upload bandwidth. If there are multiple network cards or partitions, the values collected are from the network card or partition with the highest usage rate.\n\nConnections: CurrEstab - Number of TCP connections currently in ESTABLISHED or CLOSE-WAIT state.\n\nHealth value is a new metric calculated based on CPU, memory, and IO. A score below 90 indicates that the system's resource usage needs attention. This is a metric under testing, and parameters may need to be optimized based on actual conditions.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{env=~\"$env\",job=~\"$job\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{env=~\"$env\",job=~\"$job\"})by(instance)/86400",
     "legendFormat": "Runtime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{env=~\"$env\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "node_load5{env=~\"$env\",job=~\"$job\"}",
     "legendFormat": "5min Load"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{env=~\"$env\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{env=~\"$env\",job=~\"$job\"} / (node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"})))* 100",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {env=~\"$env\",job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{env=~\"$env\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "maxRead"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{env=~\"$env\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "maxWrite"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{env=~\"$env\",job=~\"$job\"} - 0",
     "legendFormat": "Connections"
    },
    {
     "expr": "node_sockstat_TCP_tw{env=~\"$env\",job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{env=~\"$env\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "Download Bandwidth"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{env=~\"$env\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "Upload Bandwidth"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{env=~\"$env\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{env=~\"$env\",job=~\"$job\"} / node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{env=~\"$env\",job=~\"$job\"}[$interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_disk_io_time_seconds_total{env=~\"$env\",job=~\"$job\"}[$interval])) by (instance) *100",
     "legendFormat": "IO Util Usage"
    }
   ]
  },
  {
   "title": "P99 Resource Usage in Last 7 Days",
   "type": "table",
   "description": "- P99：Dataset sorted in ascending order, data at the 99th percentile position. (i.e., data at the 99% position after ascending sort)\n- This table requires adding recording rules in Prometheus (refer to dashboard download page)\n- Data will be displayed 1 hour after adding recording rules.\n- Time range [7d:1h] means viewing hourly data points over the past 7 days.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_uname_info{env=~\"$env\",job=~\"$job\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "quantile_over_time(0.99, cpu:usage:rate1m{env=~\"$env\",job=~\"$job\"}[7d:1h])",
     "legendFormat": "CPU UsageP99"
    },
    {
     "expr": "quantile_over_time(0.99, mem:usage:rate1m{env=~\"$env\",job=~\"$job\"}[7d:1h])",
     "legendFormat": "Memory UsageP99"
    }
   ]
  },
  {
   "title": "Overall Total Load and Overall AverageCPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_load5{env=~\"$env\",job=~\"$job\"})",
     "legendFormat": "5min Load"
    },
    {
     "expr": "count(node_cpu_seconds_total{env=~\"$env\",job=~\"$job\",mode='system'})",
     "legendFormat": "Cores"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{env=~\"$env\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Average%"
    }
   ]
  },
  {
   "title": "Total Memoryand overall averageMemory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"} - node_memory_MemAvailable_bytes{env=~\"$env\",job=~\"$job\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"} - node_memory_MemAvailable_bytes{env=~\"$env\",job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{env=~\"$env\",job=~\"$job\"}))*100",
     "legendFormat": "Average%"
    }
   ]
  },
  {
   "title": "Overall Total Disk and Overall Average Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=~\"$env\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "Average%"
    }
   ]
  },
  {
   "title": "Resource Details: [$show_name] [$instance]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "【$show_name】：PartitionAvailable(EXT.*/XFS/NFS)",
     "type": "table",
     "description": "this dashboardinof：disk、Usage、Available、UsageanddfofSize、Used、Avail、Use% ofvalueone，Use%ofvaluewill roundinonenumber，。\n\n：dfinUse%is：(size - free) * 100 / (avail + (size - free))，if result is divisible thenisvalue，isvalue+1，of%。\ndf：",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "legendFormat": "maxPartitionUsage({{mountpoint}})"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance\"} + 1))) * 100",
       "legendFormat": "PartitionUsage"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance\"})",
       "legendFormat": "Runtime",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'})",
       "legendFormat": "CPU Cores",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
       "legendFormat": "Total Memory",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) * 100",
       "legendFormat": "CPU iowait",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "node_filefd_maximum{instance=~\"$instance\"}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "process_max_fds{job=\"node_exporter\",instance=~\"$instance\"}",
       "legendFormat": "max",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Traffic per minute$device",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[5m])/5",
       "legendFormat": "{{device}}_inDownload"
      },
      {
       "expr": "increase(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[5m])/5",
       "legendFormat": "{{device}}_outUpload"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
       "legendFormat": "diskIOUsage"
      }
     ]
    },
    {
     "title": "Memory information",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "diskUsage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "Capacity%: {{mountpoint}}"
      },
      {
       "expr": "(1 - node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"} / node_filesystem_files{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"}) * 100",
       "legendFormat": "Inodes%: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "System average load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance\"}",
       "legendFormat": "1min Load"
      },
      {
       "expr": " sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPUTotal Cores"
      },
      {
       "expr": "node_load5{instance=~\"$instance\"}",
       "legendFormat": "5min Load"
      },
      {
       "expr": "node_load15{instance=~\"$instance\"}",
       "legendFormat": "15min Load"
      }
     ]
    },
    {
     "title": "Process running status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{instance=~\"$instance\"}",
       "legendFormat": "Running processes",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{instance=~\"$instance\"}",
       "legendFormat": "Processes blocked waiting for IO completion",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "File descriptors (FD) / Context switches per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Context switches per second"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$instance\"}",
       "legendFormat": "Total FD used"
      },
      {
       "expr": "(node_filefd_allocated{instance=~\"$instance\"}/node_filefd_maximum{instance=~\"$instance\"}) *100",
       "legendFormat": "Total FD usedratio"
      },
      {
       "expr": "(process_open_fds{instance=~\"$instance\"}/process_max_fds{instance=~\"$instance\"}) *100",
       "legendFormat": "Process FD usage ratio"
      }
     ]
    },
    {
     "title": "Time per IO read/write (reference: less than 100ms)",
     "type": "timeseries",
     "description": "Read time seconds perperdiskPartitionreadoperationspentofsecondnumber\n\nWrite time seconds perperdiskPartitionwriteoperationspentofsecondnumber\n\nIO time seconds perperdiskPartitioninputin/inputoutoperationspentofsecondnumber\n\nIO time weighted secondsperperdiskPartitioninputin/inputoutoperationspentofWeightedsecondnumber",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Write"
      }
     ]
    },
    {
     "title": "Disk read/write rate (IOPS)",
     "type": "timeseries",
     "description": "Reads completed: perperdiskPartitionpersecondreadcompletioncount\n\nWrites completed: perperdiskPartitionpersecondwritecompletioncount\n\nIO now perperdiskPartitionpersecondcurrentlyprocessingofinputin/inputoutrequestnumber",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Write"
      }
     ]
    },
    {
     "title": "Disk read/write capacity per second",
     "type": "timeseries",
     "description": "Read bytes perperdiskPartitionpersecondReadofbitnumber\nWritten bytes perperdiskPartitionpersecondWriteofbitnumber",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_Write"
      }
     ]
    },
    {
     "title": "I/O operation time ratio per second (I/O Util)",
     "type": "timeseries",
     "description": "Time spent on I/O within one second of natural time. (wall-clock time)\n\nnode_disk_io_time_seconds_total：\nSeconds spent by disk on input/output operations. This value is cumulative. (Milliseconds Spent Doing I/Os)\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate rate per second: (last value - previous last value) / timestamp difference, i.e., the proportion of time disk spends on I/O operations within 1 second.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}}_I/O operations% per second"
      }
     ]
    },
    {
     "title": "Network Socket connection information",
     "type": "timeseries",
     "description": "Sockets_used - Total number of sockets used by all protocols\n\nCurrEstab - Number of TCP connections currently in ESTABLISHED or CLOSE-WAIT state\n\nTCP_alloc - Number of allocated TCP sockets (established, sk_buff allocated)\n\nTCP_tw - Number of TCP connections waiting to close\n\nUDP_inuse - Number of UDP sockets in use\n\nRetransSegs - Number of TCP retransmitted segments\n\nOutSegs - Number of TCP segments sent\n\nInSegs - Number of TCP segments received",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\"}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$instance\"}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$instance\"}",
       "legendFormat": "Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"$instance\"}",
       "legendFormat": "UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$instance\"}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Tcp_InSegs"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Tcp_OutSegs"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Tcp_RetransSegs"
      }
     ]
    },
    {
     "title": "Network bandwidth usage per second$device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
       "legendFormat": "{{device}}_inDownload"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
       "legendFormat": "{{device}}_outUpload"
      }
     ]
    }
   ]
  }
 ]
}