{
 "title": "Kubernetes Kafka Overview",
 "description": "Kafka resource usage and consumer lag overview\r\n\r\nImproved over dashboard: 762.\r\n\r\nThis requires kafka-exporter for consumer group level metrics.",
 "tags": [ "Kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "topic_name",
    "label": "Topic",
    "query": "label_values(kafka_consumergroup_lag, topic)"
   },
   {
    "name": "group_id",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_lag{topic=\"$topic_name\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer lag by group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{consumergroup=~\"$group_id\", topic=~\"$topic_name\", topic!=\"__consumer_offsets\"}[10m]))  by (consumergroup, topic)",
     "legendFormat": "{{ consumergroup }} | {{ topic }}"
    }
   ]
  },
  {
   "title": "Offset progress",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=~\"$group_id\", topic=~\"$topic_name\", topic!=\"__consumer_offsets\"}[5m])) by (consumergroup, topic)",
     "legendFormat": "{{ consumergroup }} | {{ topic }}"
    }
   ]
  },
  {
   "title": "Topic Production rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic_name\", topic!=\"__consumer_offsets\"}[5m])) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum by(topic) (kafka_log_size)", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod) (kafka_log_size)",
     "legendFormat": "{{ kubernetes_pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"kafka\"}[1m])",
     "legendFormat": "{{kubernetes_pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(container_memory_usage_bytes{pod_name=~\"kafka-.\"}) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{app=\"kafka\"}[5m]))",
     "legendFormat": "{{ kubernetes_pod }}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesin_total{app=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesout_total{app=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "{{kubernetes_pod}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_underreplicated)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod)(rate(kafka_server_replicamanager_isrexpands_total[1m]))",
     "legendFormat": "{{kubernetes_pod}}"
    }
   ]
  }
 ]
}