app:
  namespaceOverride: system-argocd
  server:
    service:
      type: ClusterIP
  ingress:
    enabled: false
  dex:
    enabled: true
  configs:
    params:
      - name: server.insecure
        value: "true"
    secret:
      createSecret: true
    cm:
      create: true
      application.resourceTrackingMethod: server

sops:
  aws:
    defaultRegion: eu-west-3
    accessKeyId: ""
    secretAccessKey: ""
