app:
  global:
    networkPolicy:
      create: true
      defaultDenyIngress: true
  crds:
    install: true
  namespaceOverride: argocd
  server:
    service:
      type: ClusterIP
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  ingress:
    enabled: false
  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  configs:
    params:
      create: true
      annotations: {}
      enabled: true
      list:
        - name: server.insecure
          value: "true"
    secret:
      createSecret: true
    cm:
      create: true
      application.resourceTrackingMethod: server
