apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager
spec:
  groups:
  - name: cert-manager
    rules:
    - alert: CertificateNotReady
      expr: certmanager_certificate_ready_status{condition="False"} == 1
      for: 15m
      labels:
        alertowner: skyloud
        severity: critical
      annotations:
        tenant_id: "{{ $labels.tenant_id }}"
        cluster: "{{ $labels.cluster }}"
        summary: Certificate {{ $labels.name }} is not ready

    - alert: CertificateExpiringSoon
      expr: certmanager_certificate_expiration_timestamp_seconds - time() < 7 * 24 * 3600
      for: 1h
      labels:
        alertowner: skyloud
        severity: warning
      annotations:
        tenant_id: "{{ $labels.tenant_id }}"
        cluster: "{{ $labels.cluster }}"
        summary: Certificate {{ $labels.name }} expires in less than 7 days

    - alert: CertificateRenewalFailed
      expr: increase(certmanager_certificate_renewal_timestamp_seconds[1h]) == 0 and certmanager_certificate_expiration_timestamp_seconds - time() < 30 * 24 * 3600
      for: 1h
      labels:
        alertowner: skyloud
        severity: critical
      annotations:
        tenant_id: "{{ $labels.tenant_id }}"
        cluster: "{{ $labels.cluster }}"
        summary: Certificate {{ $labels.name }} renewal has failed
