{{- if .Values.imageUpdater.enabled }}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ include "common.fullname" $ }}
  namespace: {{ .Values.imageUpdater.applicationNamespace}}
spec:
  applicationRefs:
    - namePattern: {{ .Release.Name | quote }}
      writeBackConfig:
        method: {{ .Values.imageUpdater.writeBackConfig.method | quote }}
        gitConfig:
          repository: {{ .Values.imageUpdater.writeBackConfig.gitConfig.repository | quote }}
          branch: {{ .Values.imageUpdater.writeBackConfig.gitConfig.branch | quote }}
          writeBackTarget: {{ .Values.imageUpdater.writeBackConfig.gitConfig.writeBackTarget | quote }}
      images:
        - alias: {{ .Values.imageUpdater.image.alias | quote }}
          imageName: {{ .Values.image.repository | quote }}
          commonUpdateSettings:
            updateStrategy: {{ .Values.imageUpdater.image.updateStrategy | quote }}
          manifestTargets:
            helm:
              name: {{ .Values.imageUpdater.image.manifestTargets.helm.nameKey | quote }}
              tag: {{ .Values.imageUpdater.image.manifestTargets.helm.tagKey | quote }}
{{- end }}
