{
 "title": "Longhorn Global Overview",
 "description": "High-level view of Longhorn - useful for monitoring, alerting and troubleshooting.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "description": "The total number of nodes in the Longhorn storage system",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(longhorn_node_count_total) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Schedulable Nodes",
   "type": "stat",
   "description": "Schedulable nodes are nodes that Longhorn can use their storage for replica scheduling.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(longhorn_node_status{condition=\"schedulable\"}==1) OR on() vector(0)) - (count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Disabled Nodes",
   "type": "stat",
   "description": "Disabled nodes are nodes that are disabled by the user.  When users disable a node, Longhorn will not use the node's storage for replica scheduling. Note that Longhorn can still attach a volume to disabled nodes because the actual data of the volume could be on a different node.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Failed Nodes",
   "type": "stat",
   "description": "Failed Nodes are nodes that Longhorn cannot attach volumes to and cannot schedule replicas onto. e.g: when the nodes went down.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(longhorn_node_count_total) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"}==1) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Attached Volumes",
   "type": "stat",
   "description": "Attached volumes are volumes that are currently attaching to a node",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Detached Volumes",
   "type": "stat",
   "description": "Detached volumes are volumes that aren't currently attaching to a node",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Degraded Volumes",
   "type": "stat",
   "description": "Degraded volumes are volumes that have the number of healthy replicas smaller than the expected number of replicas. e.g. User creates a volume with 2 replicas but 1 replicas is failed.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Faulty Volumes",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Node Capacity",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_node_storage_capacity_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "longhorn_disk_capacity_bytes", "legendFormat": "{{disk}}" }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "table",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (volume) (longhorn_volume_capacity_bytes)",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Node Storage Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_disk_usage_bytes/longhorn_disk_capacity_bytes)*100",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Volumes Per Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (node) (longhorn_volume_state==2)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Volume Size/Capacity",
   "type": "timeseries",
   "description": "Note that Longhorn volume actual size is not the size of the filesystem inside a Longhorn volume.  See more at : https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (avg by (volume) (longhorn_volume_actual_size_bytes))/ (avg by (volume) (longhorn_volume_capacity_bytes)) ) *100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Volume Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "longhorn_volume_write_throughput",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Volume Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "longhorn_volume_read_throughput",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "longhorn_volume_write_iops", "legendFormat": "{{volume}}" }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "longhorn_volume_read_iops", "legendFormat": "{{volume}}" }
   ]
  },
  {
   "title": "Volume Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "longhorn_volume_write_latency", "legendFormat": "{{volume}}" }
   ]
  },
  {
   "title": "Volume Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "longhorn_volume_read_latency", "legendFormat": "{{volume}}" }
   ]
  },
  {
   "title": "Node CPU Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( longhorn_node_memory_usage_bytes / longhorn_node_memory_capacity_bytes ) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Longhorn Manager CPU Usage",
   "type": "timeseries",
   "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "milicpu" } },
   "targets": [
    {
     "expr": "longhorn_manager_cpu_usage_millicpu",
     "legendFormat": "{{manager}}"
    }
   ]
  },
  {
   "title": "Longhorn Manager Memory Usage",
   "type": "timeseries",
   "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_manager_memory_usage_bytes",
     "legendFormat": "{{manager}}"
    }
   ]
  },
  {
   "title": "Instance Manager CPU Usage",
   "type": "timeseries",
   "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "milicpu" } },
   "targets": [
    {
     "expr": "longhorn_instance_manager_cpu_usage_millicpu",
     "legendFormat": "{{instance_manager}}"
    }
   ]
  },
  {
   "title": "Instance Manager Memory Usage",
   "type": "timeseries",
   "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_instance_manager_memory_usage_bytes",
     "legendFormat": "{{instance_manager}}"
    }
   ]
  }
 ]
}