apiVersion: v2
name: cloudnative-pg
version: 0.23.0
type: application
dependencies:
  - name: cloudnative-pg
    version: ~0.23.0
    repository: "https://cloudnative-pg.github.io/charts"
    alias: app
