apiVersion: v2
name: grafana-alloy
version: 1.5.1
type: application
dependencies:
  - name: alloy
    version: ~1.4.0
    repository: "https://grafana.github.io/helm-charts"
    alias: app
    condition: app.enabled
  - name: alloy
    version: ~1.4.0
    repository: "https://grafana.github.io/helm-charts"
    alias: logs
    condition: logs.enabled
  - name: alloy
    version: ~1.4.0
    repository: "https://grafana.github.io/helm-charts"
    alias: metrics
    condition: metrics.enabled
