app:
  enabled: true
  alloy:
    mounts:
      dockercontainers: true
      varlog: true
  serviceMonitor:
    enabled: true
  controller:
    nodeSelector: {}
    tolerations: []

logs:
  enabled: false
  alloy:
    mounts:
      dockercontainers: true
      varlog: true
  serviceMonitor:
    enabled: true
  controller:
    type: daemonset
    nodeSelector: {}
    tolerations: []

metrics:
  enabled: false
  crds:
    create: false
  alloy:
    clustering:
      enabled: true
    mounts:
      dockercontainers: false
      varlog: false
  serviceMonitor:
    enabled: true
  controller:
    type: statefulset
    nodeSelector: {}
    tolerations: []
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
