app:
  alloy:
    controller:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: []
    mounts:
      dockercontainers: true
      varlog: true
    serviceMonitor:
      enabled: true