app:
  alloy:
    controller:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: []
    mounts:
      dockercontainers: true
      varlog: true
############Keep ? No Ressource Limits by default
    resources:
      limits:
        cpu: 2500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
###########################
    serviceMonitor:
      enabled: true