apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-exporter
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 30s
  selector:
    matchLabels:
      app: event-exporter
      version: v1
