app:
  cluster:
    instances: 1
    storage:
      size: 1Gi
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    postgresql:
      parameters:
        shared_buffers: "128MB"
        max_connections: "100"
        effective_cache_size: "256MB"
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
