apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    kubeQPS: 100
    kubeBurst: 500
    maxEventAgeSeconds: 600
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        stdout: {}
