---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-plugin-k8s
data:
  sops-k8s.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-sops-plugin-k8s
    spec:
      # Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
      # if this looks like a Helm chart
      discover:
        find:
          command:
            - "/home/argocd/cmp-server/config/plugin.sh" 
            - "discover"
      generate:
        command:
          - "/home/argocd/cmp-server/config/plugin.sh" 
          - "generate"
      lockRepo: true
  sops-k8s.sh: |
    #!/usr/bin/bash

    set -e

    main () {
      if [[ "$1" == "discover" ]] ; then
        find . -type f -name '*.yaml' | grep '\.enc\.yaml'
        return 0
      fi

      if [[ "$1" == "generate" ]] ; then
        find . -type f -name '*.enc.yaml' -exec echo '---' \; -exec sops -d {} \;
        find . -type f -name '*.yaml' -not -name '*.enc.yaml' -exec echo '---' \; -exec cat {} \;
        return 0
      fi

      return 1
    }

    main "$@"
